let NewProducts = 
    [
        {
         "name": "SCULPFUN 30L/Min 200-240V Air Pump Compressor for Laser Engraver",
         "description": "SCULPFUN 30L/Min 200-240V Air Pump Compressor for Laser Engraver, Adjustable Speed Low Noise Low Vibration - EU Plug",
         "price": "$115.95",
         "ratings": "121",
         "imgURL": "https://m.media-amazon.com/images/I/61h3+gsxWHL._AC_UF894,1000_QL80_.jpg",
         "whislist": "12",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"Europe"
         
        },
        {
         "name": "Creality Smart Kit 2.0 Wifi Box",
         "description": "Creality Smart Kit 2.0 Wifi Box, Cloud Slice, Cloud Printing, WiFi Box , 1080P Web Camera, Remote Control",
         "price": "$86.96",
         "cutprice": "$94.87",
         "off": "(8% off)",
         "ratings": "110",
         "imgURL": "https://www.pngall.com/wp-content/uploads/2017/03/Handicraft-Transparent.png",
         "whislist": "4",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"Poland"
        },
        {
         "name": "Mini Wireless Camera Real 1080P Wifi Camera",
         "description": "Mini Wireless Camera Real 1080P Wifi Camera Home Nanny Tiny Cam Baby with Night Vision Motion Cell Phone App Detection - Black",
         "price": "$19.75",
         "ratings": "99",
         "imgURL": "https://indi-craft.com/wp-content/uploads/2020/03/Indi_Craft.png",
         "whislist": "9",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Germany"
        },
        {
         "name": "Tronsmart T7 Mini 15W TWS Bluetooth Speaker",
         "description": "Tronsmart T7 Mini 15W TWS Bluetooth Speaker, Balanced Bass, IPX7 Waterproof, LED Modes",
         "price": "$35.57",
         "cutprice": "$52.70",
         "off": "(33% off)",
         "ratings": "89",
         "imgURL": "https://www.shutterstock.com/image-photo/top-view-close-beautiful-gujarati-260nw-1340429582.jpg",
         "whislist": "14",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"Spain"
        },
        {
         "name": "Q9 Pro GT2 Smartwatch 1.85'' TFT HD Touch Screen",
         "description": "Q9 Pro GT2 Smartwatch 1.85'' TFT HD Touch Screen BT5.0 Heart Rate Blood Pressure SpO2 Monitor Fitness Tracker - Black&Gold",
         "price": "$31.60",
         "ratings": "78",
         "imgURL": "https://5.imimg.com/data5/TM/BI/MY-2683192/wooden-carving-500x500.jpg",
         "whislist": "4",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"United_States"
        },
        {
         "name": "360 Degree Rotatable 1080p HD Camera",
         "description": "360 Degree Rotatable 1080p HD Camera, WiFi Wireless Smart Night Vision Camera, 2-way Voice AP Connection - EU Plug",
         "price": "$25.03",
         "ratings": "67",
         "imgURL": "https://assets.architecturaldigest.in/photos/6008382b94ca758bb0ad0f8f/master/w_1600%2Cc_limit/indian-crafts_5-3.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"no",
         "shipping":"yes",
         "country":"United_Kingdom"
        },
        {
         "name": "3.5 Inch IPS TYPE-C Secondary Screen CPU",
         "description": "3.5 Inch IPS TYPE-C Secondary Screen CPU GPU RAM HDD Monitoring USB Display",
         "price": "$48.75",
         "ratings": "120",
         "imgURL": "https://i.pinimg.com/originals/56/b0/be/56b0be2640b5726f76b975d7be28a975.jpg",
         "whislist": "5",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"Netherland"
        },
        {
         "name": "ORTUR Laser Engraving Y-axis Rotary Roller",
         "description": "ORTUR Laser Engraving Y-axis Rotary Roller Ortur-YRR Laser Master Part to Engrave on Cans, Eggs, Cylinders",
         "price": "$105.41",
         "ratings": "131",
         "imgURL": "https://i.ytimg.com/vi/aWSpHXldAT0/maxresdefault.jpg",
         "whislist": "5",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"China"
        },
        {
         "name": "Haylou RS4 Plus Smartwatch 1.78-Inch Retina AMOLED",
         "description": "Haylou RS4 Plus Smartwatch 1.78-Inch Retina AMOLED HD Display 105 Sports Mode SpO2 Heart Rate - Black Silver",
         "price": "$79.05",
         "cutprice": "$90.92",
         "off": "(13% off)",
         "ratings": "142",
         "imgURL": "https://5.imimg.com/data5/PY/XZ/PE/ANDROID-17379288/product-jpeg-500x500.jpg",
         "whislist": "4",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Europe"
        },
        {
         "name": "Ortur LU2-10A 10W Laser Module",
         "description": "Ortur LU2-10A 10W Laser Module, 0.07*0.06mm Compressed Spot, Fixed Focus, Air Assist Interface, For Aufero and Other Desktop Laser Engravers",
         "price": "$355.79",
         "ratings": "153",
         "imgURL": "https://tiimg.tistatic.com/fp/1/008/353/sutliyan-handcrafted-multicolor-regular-shoulder-tote-bag-11-15-inch--572.jpg",
         "whislist": "1",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"Poland"
        },
        {
         "name": "Metal Tube Spare Part for JIMMY JV51 Vacuum Cleaner",
         "description": "Metal Tube Spare Part for JIMMY JV51 Vacuum Cleaner",
         "price": "$56.65",
         "ratings": "164",
         "imgURL": "https://www.shutterstock.com/image-photo/stacked-craft-clay-plates-ceramic-600nw-2271994401.jpg",
         "whislist": "0",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"Germany"
        },
        {
         "name": "Mibro A1 Smartwatch 1.28'' HD Touch Screen",
         "description": "Mibro A1 Smartwatch 1.28'' HD Touch Screen BT5.0 Heart Rate SpO2 Sensor, 20 Sports Modes, 5ATM Waterproof - Black",
         "price": "$52.69",
         "ratings": "175",
         "imgURL": "https://5.imimg.com/data5/SELLER/Default/2023/4/303164406/VU/IP/JE/20951053/table-top-wooden-jau-kandhei-500x500.jpg",
         "whislist": "5",
         "arrived":"30",
         "sale":"no",
         "shipping":"yes",
         "country":"Spain"
        },
        {
         "name": "Hawkeye Firefly Q7 120 Degree Wide Angle 1080P 30FPS HD Mini WiFi",
         "description": "Hawkeye Firefly Q7 120 Degree Wide Angle 1080P 30FPS HD Mini WiFi FPV Action Sport Camera Aerial Camcorder - Black",
         "price": "$73.78",
         "cutprice": "$88.28",
         "off": "(16% off)",
         "ratings": "186",
         "imgURL": "https://m.media-amazon.com/images/I/619A+FMwqzL._AC_UF1000,1000_QL80_.jpg",
         "whislist": "4",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"United_States"
        },
        {
         "name": "3PCS Dust Bag for Roborock",
         "description": "3PCS Dust Bag for Roborock Q7 MAX+/S7 MAXV Ultra Automatic Suction Station",
         "price": "$19.75",
         "ratings": "198",
         "imgURL": "https://5.imimg.com/data5/YW/AV/MY-4024250/metal-craft-500x500.jpg",
         "whislist": "3",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"United_Kingdom"
        },
        {
         "name": "LOKMAT APPLLP 5 Smartwatch 4G WiFi LTE Watch",
         "description": "LOKMAT APPLLP 5 Smartwatch 4G WiFi LTE Watch with Dual Cameras 1.6'' TFT Screen RAM 4GB ROM 128GB for Android and iOS",
         "price": "$312.29",
         "ratings": "212",
         "imgURL": "https://2.imimg.com/data2/QS/WF/MY-5007340/bamboo-jewellery-250x250.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Netherland"
        },
        {
         "name": "LEMFO LF31 Smartwatch BT Calling Watch",
         "description": "LEMFO LF31 Smartwatch BT Calling Watch 1.32'' Touch Screen, HR, SpO2, BP Monitor, NFC for Android iOS - Black Steel",
         "price": "$57.96",
         "ratings": "23",
         "imgURL": "https://theheritageartifacts.com/cdn/shop/files/DSC_8426_2000x2667.jpg?v=1701450288",
         "whislist": "3",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"China"
        },
        {
         "name": "Haylou LS09A Smartwatch 1.28-Inch TFT Display",
         "description": "Haylou LS09A Smartwatch 1.28-Inch TFT Display BT5.1 SpO2 Heart Rate,Sleep Monitor 12 Sports Modes",
         "price": "$52.70",
         "ratings": "98",
         "imgURL": "https://m.media-amazon.com/images/I/81qE+AGCpsL._AC_UF350,350_QL80_.jpg",
         "whislist": "3",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"Poland"
        },
        {
         "name": "Haylou RS3 LS04 Smartwatch 1.2-Inch AMOLED HD Display",
         "description": "Haylou RS3 LS04 Smartwatch 1.2-Inch AMOLED HD Display BT5.0 GPS Fitness Tracker 14 Workout Modes",
         "price": "$94.86",
         "ratings": "45",
         "imgURL": "https://m.media-amazon.com/images/I/31F9Bxh5SIL.jpg",
         "whislist": "3",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"Europe"
        },
        {
         "name": "Raspberry Pi 4 Model B 8GB RAM ",
         "description": "Raspberry Pi 4 Model B 8GB RAM BCM2711 Quad Core Cortex-A72 ARM v8 1.5GHz Support 2.4/5.0 GHz WiFi Bluetooth 5.0 - 8GB",
         "price": "$365.02",
         "ratings": "56",
         "imgURL": "https://www.brassgiftonline.com/s/5fa28c32f990d2c26c566c66/64b412c67e102ae640d808a8/bs1370-c_1.jpg",
         "whislist": "2",
         "arrived":"7",
         "sale":"no",
         "shipping":"yes",
         "country":"Germany"
        },
        {
         "name": "Brass Kanchipuram Kamakshi single petal lamp / diya",
         "description": "This holy lamp also known as the Deepam of Devi Kamakshi. The Divine Lamp is dedicated to the Goddess because her statute engraved on the lamp. It is an essential addition to the prayer room in most Indian households.",
         "price": "$790.67",
         "cutprice": "$932.99",
         "off": "(15% off)",
         "ratings": "87",
         "imgURL": "https://m.media-amazon.com/images/I/81eabl8NUPL._AC_UF350,350_QL50_.jpg",
         "whislist": "3",
         "arrived":"15",
         "sale":"yes",
         "shipping":"no",
         "country":"Spain"
        },
        {
         "name": "Dokra Art Lantern / Hurricane Decorative",
         "description": "ThisÂ elegant and uniqueÂ Lantern made with Dokra art formÂ will give a raw, rustic appeal to your home decor. Place a candle inside and see the beauty of the lights pouring outside and the reflection of the shadows on your wall. A handle also is provided in case you want to use it as a hanging lamp.",
         "price": "$263.55",
         "ratings": "299",
         "imgURL": "https://cdn.vibecity.in/providers/6440e26b23e68e01d89f561a/4ef11a76-088c-4962-b97c-78dac28b576e_b4c584bc-5d22-422f-bf79-f6fa35217c7f-3X.png",
         "whislist": "3",
         "arrived":"30",
         "sale":"no",
         "shipping":"yes",
         "country":"United_States"
        },
        {
         "name": "Natural Horn Bowl, For Home",
         "description": "Owing to the efforts of our dedicated team of professionals, we have been constantly engaged in offering the best quality Buffalo Horn Bowl.",
         "price": "$22.39",
         "ratings": "234",
         "imgURL": "https://5.imimg.com/data5/SELLER/Default/2022/11/HC/SV/CQ/51121430/natural-horn-bowl-500x500.jpg",
         "whislist": "2",
         "arrived":"7",
         "sale":"yes",
         "shipping":"no",
         "country":"United_Kingdom"
        },
        {
         "name": "Designer Marble Chakla Belan, For Home",
         "description": "Try using our all new Indian Traditional Designer Marble Rolling Pin Board. Board :pure white marble with design enamel coating on it Roller pin:pure mango wood with design enamel coating.",
         "price": "$316.26",
         "ratings": "63",
         "imgURL": "https://5.imimg.com/data5/SELLER/Default/2021/3/KQ/BM/HT/82789292/wedding-printed-marble-chakla-belan.jpg",
         "whislist": "1",
         "arrived":"15",
         "sale":"no",
         "shipping":"yes",
         "country":"Netherland"
        },
        {
         "name": "Wooden Handmade jewelry Box",
         "description": "Handmade Wooden Box, Full Meenakari Work Box, Dry Fruit Box, Jewelry Box, Multi Use Box, Best Gift Item, Home Decor, Housewarming Gift",
         "price": "$197.66",
         "ratings": "72",
         "imgURL": "https://i.etsystatic.com/18714651/r/il/459b0b/4205258759/il_570xN.4205258759_rfyp.jpg",
         "whislist": "1",
         "arrived":"30",
         "sale":"yes",
         "shipping":"no",
         "country":"China"
        },
        {
            "name": "JHE White Marble Pen Stand for Home and Office Use",
            "description": "This beautiful article is from the house of Jagrati Enterprises.About Product : - This beautiful product is perfect addition for your home. Made with premium best class Material. Uses:- As showpiece in Your Home, Garden, balcony or in Meditation area.Country of Origin : India",
            "price": "$817.02",
            "cutprice": "$1035.78",
            "off": "(21% off)",
            "ratings": "89",
            "imgURL": "https://images.meesho.com/images/products/175730166/jyeoz_512.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"no",
            "shipping":"yes",
            "country":"Poland"
           },
           {
            "name": "Handicraft Beautiful White Marble Photo Frame Inlay Art",
            "description": "Display your memories, pictures and collection in this Decorative Square Photo Frame with Flowers and peacock work. Etched on a white marble it sports a beautiful finish and lends a stunning appeal. The classic look of colorful flowers let your photograph shine and make it special part of home decor and center of attention. Its versatile design, Intricate artistry and superlative craftsmanship makes this ideal for unique gift to your loved ones, family and friends. This marble photo frame is diligently handcrafted by skilled artisans",
            "price": "$55.33",
            "ratings": "33",
            "imgURL": "https://images.meesho.com/images/products/237110972/e8eou_512.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"Europe"
           },
           {
            "name": "White Marble Inlay Work Jewellery Box For Home Decorative Showpiece",
            "description": "This Octangular White Marble Necklace Holder is made from many piece of marble and its inlaid with Paua Shell, Carnelian, Coral, Jasper, Lapislazuli, and Turquoise. The Octangular White Marble Necklace Holder is made in Agra India & fully handmade. This Octangular White Marble Necklace Holder can be used for jewelry, visiting card & also can be used for decoration on coffee table & dressing table. This antique jewelry box illuminates if the light arrangement(Battery LED) is made under the box as you can see the beauty of light illumination in the photographs of the box. Your invaluable pieces of jewelry can now be placed in an exquisite box that will enhance the value of the jewelry and give it the respect it deserves. The versatile antique jewelry box may be used as a small jewelry box and keepsake box or presentation box. The art piece will be delivered by Fedex or Dhl free of cost door to door.",
            "price": "$18.44",
            "ratings": "45",
            "imgURL": "https://www.artefactindia.com/image/cache/catalog/box/jewelry%20box/043/marble%20ring%20box-1000x1000.JPG",
            "whislist": "0",
            "arrived":"30",
            "sale":"no",
            "shipping":"yes",
            "country":"Germany"
           },
           {
            "name": "Traditional Meenakari Style Hand Painted Tea Kettle",
            "description": "Unique hand painted art piece which adds an artistic essence to your home and kitchen. Do not use heat or microwave. Do not use for cooking. Use for serving and home décor. Clean with normal water and pat dry the outside part. Use of scrub or detergents might damage the painting work.",
            "price": "$56.65",
            "cutprice": "$63.24",
            "off": "(10% off)",
            "ratings": "55",
            "imgURL": "https://i.etsystatic.com/8101765/r/il/4cd4c6/2711746116/il_570xN.2711746116_tmt1.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"yes",
            "shipping":"no",
            "country":"Spain"
           },
           {
            "name": "Meenakari and Kundan Work Metal Tortoise Decorative Showpiece",
            "description": "Bring home this decorative aluminium Tortoise enamel painted with Meenakari and Kundan work. The royal masterpiece elevates the beauty wherever it is kept and makes the home ambience class apart with it's traditional and contemporary appeal. ",
            "price": "$47.43",
            "ratings": "213",
            "imgURL": "https://5.imimg.com/data5/SELLER/Default/2022/4/YY/XF/PA/149848351/aapno-rajasthan-multicolour-metal-meenakari-tortoise-hand-crafted-statue-showpiece-aapno-rajasthan-m-prtnik.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"no",
            "shipping":"yes",
            "country":"United_States"
           },
           {
            "name": "Antique Gold finish Idol of Lord Ganesh reading book on a easy chair",
            "description": "Stylish idol of Lord Ganesh, relaxing and reading book on a easy chair, handcrafted on aluminum with a oxidised gold finish. A very auspicious decor piece to be placed in your living room or office.",
            "price": "$104.09",
            "ratings": "155",
            "imgURL": "https://images.meesho.com/images/products/247327469/zjuwg_512.webp",
            "whislist": "0",
            "arrived":"30",
            "sale":"yes",
            "shipping":"no",
            "country":"United_States"
           },
           {
            "name": "Handicraft Decorative Soft Cotton Cloth",
            "description": " Handicraft Decorative Soft Cotton Cloth Unstitched Dress Materials for Women with Floral Print Fabric for Sofa, Upholstery, Curtains, Cushions, and Craft Multicolor 10 Meter",
            "price": "$421.68",
            "cutprice": "$474.39",
            "off": "(11% off)",
            "ratings": "176",
            "imgURL": "https://m.media-amazon.com/images/I/91U3Y-JiPFL.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"no",
            "shipping":"yes",
            "country":"Netherland"
           },
           {
            "name": "Marble mobile holder with clock - Red and Gold motifs",
            "description": "Suitable for any kind of mobile, the tilted form gives an easier view of your mobile while it rests on the holder. A bonus is the attachment of analogue clock mechanism with metal frame. ",
            "price": "$21.07",
            "ratings": "59",
            "imgURL": "https://m.media-amazon.com/images/I/61hsk4SaOgL.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"China"
           },
           {
            "name": "Analog Iron Red Antique Wall Clock",
            "description": "Established as Sole Proprietorship firm in the year 2019 at Jodhpur (Rajasthan, India), we “Rudra Arts And Crafts” are a renowned Manufacturer of premium quality range of Floor Lamp, Table Lamp, Wall Clock, etc.",
            "price": "$39.52",
            "cutprice": "$52.70",
            "off": "(25% off)",
            "ratings": "249",
            "imgURL": "https://5.imimg.com/data5/BS/LC/BE/SELLER-86208321/red-antique-wall-clock.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"no",
            "shipping":"yes",
            "country":"Poland"
           },
           {
            "name": "Glass Crafted Electric Diffuser with Colorful Lights - Assorted Designs",
            "description": "This product can be used as night lamp as well as an aroma diffuser. It makes the room look beautiful and colourful when turned on because of the colored glass. Essential oils or camphor of personal preference can be used along the with night lamp which evenly distributes the aroma around the room. It helps you to sleep better, improve your mood and feel relaxed. ",
            "price": "$60.61",
            "cutprice": "$72.47",
            "off": "(16% off)",
            "ratings": "149",
            "imgURL": "https://images.meesho.com/images/products/170829733/avtpq_512.webp",
            "whislist": "0",
            "arrived":"7",
            "sale":"yes",
            "shipping":"no",
            "country":"Europe"
           },
           {
            "name": "GREEN TIME K1 Pro Alarm Clock Radio",
            "description": "GREEN TIME K1 Pro Alarm Clock Radio, LCD Temperature Display, Electronic Digital Clock with USB Charging Port - White",
            "price": "$39.52",
            "cutprice": "$46.11",
            "off": "(14% off)",
            "ratings": "119",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-K1-Pro-Alarm-Clock-Radio-White-501648-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"no",
            "shipping":"yes",
            "country":"Germany"
           },
           {
            "name": "GREEN TIME T2 Dual USB Charging Alarm Clock",
            "description": "GREEN TIME T2 Dual USB Charging Alarm Clock Wireless Radio, LCD Screen Perpetual Calendar, Temperature Display - White",
            "price": "$39.52",
            "cutprice": "$43.47",
            "off": "(9% off)",
            "ratings": "59",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-T2-Alarm-Clock-Radio-White-501646-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"yes",
            "shipping":"no",
            "country":"Spain"
           },
           {
            "name": "GREEN TIME M9 Electronic Alarm Clock Speaker",
            "description": "GREEN TIME M9 Electronic Alarm Clock Speaker, Multifunctional Bedside Radio, Desktop Charging Bluetooth Audio - EU Plug",
            "price": "$47.43",
            "cutprice": "$51.38",
            "off": "(8% off)",
            "ratings": "69",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-M9-Electronic-Alarm-Clock-Speaker-EU-Plug-501644-0._w280_.jpg",
            "whislist": "0",
            "arrived":"7",
            "sale":"no",
            "shipping":"yes",
            "country":"United_States"
           },
           {
            "name": "GREEN TIME X7 Wireless Fast Charger Alarm Clock Radio",
            "description": "GREEN TIME X7 Wireless Fast Charger Alarm Clock Radio, LED Smart Digital Desktop, Subwoofer Bluetooth Speaker - EU Plug",
            "price": "$56.65",
            "cutprice": "$65.88",
            "off": "(14% off)",
            "ratings": "79",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-X7-Bluetooth-Charger-Alarm-Clock-Radio-EU-Plug-501643-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"United_Kingdom"
           },
           {
            "name": "GREEN TIME M7-QI Bluetooth Alarm Clock Speaker",
            "description": "GREEN TIME M7-QI Bluetooth Alarm Clock Speaker, Mobile Phone Wireless Charging, U Disk TF Card Play, FM Radio - Black",
            "price": "$65.88",
            "cutprice": "$89.60",
            "off": "(26% off)",
            "ratings": "99",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-M7-QI-Bluetooth-Alarm-Clock-Speaker-Black-501618-0._w280_.jpg",
            "whislist": "0",
            "arrived":"30",
            "sale":"no",
            "shipping":"yes",
            "country":"Netherland"
           },
           {
            "name": "GREEN TIME X10 Bluetooth 5.0 Alarm Clock Speaker",
            "description": "GREEN TIME X10 Bluetooth 5.0 Alarm Clock Speaker Bedside Night Light, LED Display Computer Audio, FM Radio - Black",
            "price": "$43.47",
            "cutprice": "$51.38",
            "off": "(15% off)",
            "ratings": "89",
            "imgURL": "https://img.gkbcdn.com/p/2022-06-08/GREEN-TIME-X10-Bluetooth-Alarm-Clock-Speaker-Black-501614-0._w280_.jpg",
            "whislist": "0",
            "arrived":"15",
            "sale":"yes",
            "shipping":"no",
            "country":"China"
           }
]


localStorage.setItem("NewProducts",JSON.stringify(NewProducts))


let BestSeller = [
    {
        "name": "Zonestar Z9V5 MK3 3D Printer Auto Leveling Adjustable",
        "description": "Zonestar Z9V5 MK3 3D Printer Auto Leveling Adjustable 4 Extruder Design Mix-Color Printing Resume Printing",
        "price": "$764.31",
        "cutoff": "$952.76",
        "off": "(20% off)",
        "ratings": "18",
        "imgURL": "https://img.gkbcdn.com/p/2022-04-22/Zonestar-Z9V5-MK3-3D-Printer-499936-0._w280_.jpg",
        "wishlist": "5",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "FIIDO M1 Pro 12.8Ah 48V 500W 20 Inches Folding Moped Bicycle",
        "description": "FIIDO M1 Pro 12.8Ah 48V 500W 20 Inches Folding Moped Bicycle 40km/h Top Speed 130KM Mileage Range Electric Bike",
        "price": "$1647.24",
        "cutoff": "$1955.60",
        "off": "(16% off)",
        "ratings": "119",
        "imgURL": "https://img.gkbcdn.com/p/2022-04-09/FIIDO-M1-Pro-12-8Ah-48V-500W-499384-0._w280_.jpg",
        "wishlist": "7",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "FIIDO T1 Cargo Electric Bike 750W Power",
        "description": "FIIDO T1 Cargo Electric Bike 750W Power 50km/h Max Speed 48V 20AH Lithium Battery 150km Range Shock Absorber - Green",
        "price": "$2174.36",
        "cutoff": "$2577.60",
        "off": "(16% off)",
        "ratings": "78",
        "imgURL": "https://img.gkbcdn.com/p/2022-04-09/b195caaecd76491aac56e51460569c35-499383-0._w280_.jpg",
        "wishlist": "4",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Black",
        "price": "$52.70",
        "ratings": "25",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-1-75mm-496660-0._w280_.jpg",
        "wishlist": "2",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - White",
        "price": "$52.70",
        "ratings": "118",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496645-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Olive Green",
        "price": "$52.70",
        "ratings": "219",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496650-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Navy Blue",
        "price": "$52.70",
        "ratings": "217",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-1-75mm-496655-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Aqua Blue",
        "price": "$52.70",
        "ratings": "117",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496665-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Gray",
        "price": "$52.70",
        "ratings": "114",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-496670-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "ERYONE Matte PLA Filament for 3D Printer",
        "description": "ERYONE Matte PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Lilac Purple",
        "price": "$52.70",
        "ratings": "98",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Matte-PLA-Filament-for-3D-Printer-1-75mm-496675-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "ERYONE Star One 3D Printer Auto-Leveling",
        "description": "ERYONE Star One 3D Printer Auto-Leveling, Super Quiet 3D Printer with TMC2208, 32Bit Motherboard FDM Forming Technology",
        "price": "$446.72",
        "ratings": "23",
        "imgURL": "https://img.gkbcdn.com/p/2022-05-27/ERYONE-Star-One-3D-Printer-501374-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE M2 Filament Dryer Box for 3D Printer Filament",
        "description": "ERYONE M2 Filament Dryer Box for 3D Printer Filament, Filament Storage Holder, Spool Storage Box, Temperature Adjustment",
        "price": "$72.47",
        "ratings": "56",
        "imgURL": "https://img.gkbcdn.com/p/2022-06-03/ERYONE-M2-Filament-Dryer-Box-501494-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Bronze",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "34",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-14/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496548-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Blue",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "187",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-15/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496569-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Gold",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "116",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-15/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496581-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Red",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "62",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-16/ERYONE-Silk-PLA-Filament-for-3D-Printer-496605-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Red Copper",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "267",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-16/ERYONE-Silk-PLA-Filament-for-3D-Printer-496610-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Silver",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "69",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-16/ERYONE-Silk-PLA-Filament-for-3D-Printer-496620-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - White",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "234",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496628-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE Silk PLA Filament for 3D Printer",
        "description": "ERYONE Silk PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - Pink",
        "price": "$39.52",
        "cutoff": "$48.75",
        "off": "(19% off)",
        "ratings": "222",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-17/ERYONE-Silk-PLA-Filament-for-3D-Printer-1-75mm-496633-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - White",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "65",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496793-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Orange",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "234",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496798-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Black",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "133",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496803-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Red",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "44",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496808-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Yellow",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "56",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496813-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool- Grey",
        "price": "$35.57",
        "cutoff": "CA$40.84",
        "off": "(13% off)",
        "ratings": "65",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496818-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mmTolerance 0.03mm 1KG(2.2LBS)/Spool - Blue",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "87",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496823-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Transparent Red",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "212",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496828-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "ERYONE PETG Filament for 3D Printer",
        "description": "ERYONE PETG Filament for 3D Printer 1.75mm Tolerance 0.03mm 1KG(2.2LBS)/Spool - Transparent Blue",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "156",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-21/ERYONE-PETG-Filament-for-3D-Printer-1-75mm-496833-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "ERYONE PLA Filament for 3D Printer",
        "description": "ERYONE PLA Filament for 3D Printer 1.75mm Tolerance 0.03mm 1kg (2.2LBS)/Spool - White",
        "price": "$35.57",
        "cutoff": "$40.84",
        "off": "(13% off)",
        "ratings": "134",
        "imgURL": "https://img.gkbcdn.com/p/2022-02-23/ERYONE-PLA-Filament-for-3D-Printer-1-75mm-496852-0._w280_.jpg",
        "wishlist": "0",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "Tronsmart Element Mega SoundPulse™ Bluetooth",
        "description": "Tronsmart Element Mega SoundPulse™ Bluetooth 5.0 Speaker with Powerful 40W Max Output 3D Digital Sound TWS Intuitive Touch Control - Black",
        "price": "$57.97",
        "cutoff": "$88.28",
        "off": "(34% off)",
        "ratings": "328",
        "imgURL": "https://img.gkbcdn.com/p/2019-01-31/tronsmart-element-mega-bluetooth-speaker-black-1571991584812._w280_.jpg",
        "wishlist": "1289",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "MX3-L-M Backlight & Voice Input 6-Axis Gyro ",
        "description": "MX3-L-M Backlight & Voice Input 6-Axis Gyro 2.4GHz Wireless Air Mouse QWERTY Keyboard with IR Learning Remote Control for Android/Windows/Linux Systems - Black",
        "price": "$18.44",
        "ratings": "11",
        "imgURL": "https://img.gkbcdn.com/p/2017-11-25/mx3-l-m-backlight-voice-input-2-4ghz-wireless-air-mouse-1571989128244._w280_.jpg",
        "wishlist": "231",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      },
      {
        "name": "Tronsmart Force SoundPulse™ 40W Bluetooth",
        "description": "Tronsmart Force SoundPulse™ 40W Bluetooth 5.0 Speaker IPX7 Water Resistant Siri TWS & NFC 15 Hours Playtime",
        "price": "$75.10",
        "cutoff": "$92.23",
        "off": "(19% off)",
        "ratings": "219",
        "imgURL": "https://img.gkbcdn.com/p/2019-01-31/tronsmart-element-force-portable-bluetooth-speaker-1571993707403._w280_.jpg",
        "wishlist": "661",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Europe"
      },
      {
        "name": "Tronsmart Element T6 Plus Portable Bluetooth",
        "description": "Tronsmart Element T6 Plus Portable Bluetooth 5.0 Speaker with 40W Max Output, Deep Bass, IPX6 Waterproof, TWS - Black",
        "price": "$79.05",
        "cutoff": "$105.41",
        "off": "(25% off)",
        "ratings": "211",
        "imgURL": "https://img.gkbcdn.com/p/2019-03-18/tronsmart-element-t6-plus-bluetooth-speaker-black-1574132869322._w280_.jpg",
        "wishlist": "631",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"Poland"
      },
      {
        "name": "Xiaomi WiFi Amplifier Pro 2X2 External Antenna",
        "description": "Xiaomi WiFi Amplifier Pro 2X2 External Antenna 300Mbps Support 64 Devices Simultaneous Link - Black",
        "price": "$26.34",
        "cutoff": "$35.57",
        "off": "(26% off)",
        "ratings": "120",
        "imgURL": "https://img.gkbcdn.com/p/2017-07-26/xiaomi-wifi-amplifier-pro-black-1574132393616._w280_.jpg",
        "wishlist": "888",
        "arrived":"15",
        "sale":"yes",
        "shipping":"no",
        "country":"Germany"
      },
      {
        "name": "Apods i500 Bluetooth 5.0 Pop-up Window TWS",
        "description": "Apods i500 Bluetooth 5.0 Pop-up Window TWS Earbuds Independent Usage Wireless Charging IPX5 - White",
        "price": "$19.23",
        "cutoff": "$32.93",
        "off": "(42% off)",
        "ratings": "35",
        "imgURL": "https://img.gkbcdn.com/p/2019-11-30/tws-i500-earphones-20191130100234539._w280_.jpg",
        "wishlist": "325",
        "arrived":"30",
        "sale":"no",
        "shipping":"yes",
        "country":"Spain"
      },
      {
        "name": "Tronsmart Onyx Ace Pro True Wireless Earbuds",
        "description": "Tronsmart Onyx Ace Pro True Wireless Earbuds TWS Earphones, Qualcomm QCC3040, Qualcomm aptX Adaptive, 27H Playtime, IPX5, One Key Recovery, White",
        "price": "$39.52",
        "cutoff": "$52.70",
        "off": "(25% off)",
        "ratings": "125",
        "imgURL": "https://img.gkbcdn.com/p/2020-03-18/Tronsmart-Onyx-Ace-Bluetooth-5-0-TWS-Earphones-White-899355-._w280_.jpg",
        "wishlist": "426",
        "arrived":"7",
        "sale":"yes",
        "shipping":"no",
        "country":"United_States"
      },
      {
        "name": "Tronsmart Force/Mega/T6/T6 Plus/T6 Plus Upgraded",
        "description": "Tronsmart Force/Mega/T6/T6 Plus/T6 Plus Upgraded Carrying Case Portable Travel Bag Protective Case",
        "price": "$15.80",
        "ratings": "119",
        "imgURL": "https://img.gkbcdn.com/p/2019-03-16/tronsmart-force-mega-t6-t6-plus-speaker-carry-case-1571991604256._w280_.jpg",
        "wishlist": "105",
        "arrived":"15",
        "sale":"no",
        "shipping":"yes",
        "country":"United_Kingdom"
      },
      {
        "name": "Mifo O7 Bluetooth 5.0 Qualcomm QCC3020 TWS Earphones",
        "description": "Mifo O7 Bluetooth 5.0 Qualcomm QCC3020 TWS Earphones Carbon Nanotube Dynamic Drivers Independent Usage IPX7 AAC/SBC/aptX Compatible with Alexa Siri 7 Hours Playtime - Black",
        "price": "$131.77",
        "cutoff": "$210.83",
        "off": "(38% off)",
        "ratings": "114",
        "imgURL": "https://img.gkbcdn.com/p/2019-11-15/mifo-o7-bluetooth-5-0-tws-qualcomm-qcc3020-earphones-black-1574132882676._w280_.jpg",
        "wishlist": "75",
        "arrived":"30",
        "sale":"yes",
        "shipping":"no",
        "country":"Netherland"
      },
      {
        "name": "Tronsmart T2 Plus 20W Bluetooth 5.0 Speaker",
        "description": "Tronsmart T2 Plus 20W Bluetooth 5.0 Speaker 24H Playtime NFC IPX7 Waterproof Soundbar with TWS,Siri,Micro SD",
        "price": "$43.47",
        "cutoff": "$55.33",
        "off": "(21% off)",
        "ratings": "89",
        "imgURL": "https://img.gkbcdn.com/p/2019-08-27/tronsmart-t2-plus-20w--bluetooth-5-0-speaker-tws-1571994588089._w280_.jpg",
        "wishlist": "275",
        "arrived":"7",
        "sale":"no",
        "shipping":"yes",
        "country":"China"
      }
    



]


localStorage.setItem("BestSeller",JSON.stringify(BestSeller))

console.log(NewProducts.length)